name: Java CI for Newspaper-Application module

on:
  push:
    paths:
      - 'Newspaper-Application/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'Newspaper-Application/**'
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build only 'Newspaper-Application' module
        run: mvn --projects Newspaper-Application --also-make clean install
