name: Java CI for Newspaper-Application module

on:
  push:
    branches: [ master ]   # ← ✅ Make sure this matches your actual branch name
    paths:
      - 'Newspaper-Application/**'
      - '.github/workflows/**'
      - 'pom.xml'                    # ← include this if you ever change the parent pom
  pull_request:
    branches: [ master ]
    paths:
      - 'Newspaper-Application/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build only 'Newspaper-Application' module
        run: mvn --batch-mode --projects Newspaper-Application --also-make clean install
